[links]
"zola/content/blog/just-enough-conda" = "submodules/blog-monorepo/just-enough-conda"
"zola/content/blog/lazy-dplyr" = "submodules/blog-monorepo/delayplyr"
"zola/content/blog/map-as-reduce" = "submodules/blog-monorepo/map-as-reduce"
"zola/content/blog/causal-bayes-3-pillars" = "submodules/blog-monorepo/causal-bayes-3-pillars"
"zola/content/blog/scrape-memoize-scum-data" = "submodules/blog-monorepo/scrape-memoize-scum-data"
"zola/content/blog/nonflat-priors" = "submodules/blog-monorepo/nonflat-priors"
"zola/content/blog/usable-research-repos" = "submodules/blog-monorepo/usable-research-repos"
"zola/content/blog/sugar-free-dict-union" = "submodules/blog-monorepo/sugar-free-dict-union"
"zola/content/blog/mandelbrot-recursive" = "submodules/blog-monorepo/mandelbrot-recursive"
