[project]
name = "mikedecr-website"
version = "0.1.0"
description = "Personal website"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
link = { cmd = "python -m mkd link" }
build = { cmd = "zola --root zola build", depends-on = ["link"] }
serve = { cmd = "zola --root zola serve --drafts", depends-on = ["link"] }

[dependencies]
python = ">=3.11"
zola = "==0.22.1"

[pypi-dependencies]
mkd = { path = ".", editable = true }
